import React from "react";
import MetadataDisplayStyles from "./metadataDisplay.module.css";
import MetadataSection from "./MetadataSection";

const DATASET_SECTION_DEFINITIONS = [
  {
    title: "General",
    fields: [
      { key: "uri", label: "URI" },
      { key: "description", label: "Description", emptyMessage: "No description provided" },
      { key: "identifier", label: "Identifier", emptyMessage: "No identifier provided" },
      { key: "type", label: "Type" },
      { key: "issued", label: "Issued" },
      { key: "modified", label: "Modified" },
      { key: "accrualPeriodicity", label: "Accrual Periodicity" },
    ],
  },
  {
    title: "Discovery",
    emptyMessage: "No discovery metadata provided.",
    fields: [
      { key: "keyword", label: "Keywords" },
      { key: "theme", label: "Theme" },
      { key: "healthCategory", label: "Health Category" },
      { key: "healthTheme", label: "Health Theme" },
      { key: "language", label: "Language" },
    ],
  },
  {
    title: "Responsibility and Contact",
    emptyMessage: "No responsibility or contact metadata provided.",
    fields: [
      { key: "publisher", label: "Publisher" },
      { key: "custodian", label: "Custodian" },
      { key: "contactPoint", label: "Contact Point" },
      { key: "healthDataAccessBody", label: "Health Data Access Body" },
    ],
  },
  {
    title: "Coverage",
    emptyMessage: "No coverage metadata provided.",
    fields: [
      { key: "spatial", label: "Spatial / Geographical Coverage" },
      { key: "temporal", label: "Temporal Coverage" },
    ],
  },
  {
    title: "Access and Governance",
    emptyMessage: "No access or governance metadata provided.",
    fields: [
      { key: "accessRights", label: "Access Rights" },
      { key: "applicableLegislation", label: "Applicable Legislation" },
      { key: "hasPersonalData", label: "Has Personal Data" },
      { key: "conformsTo", label: "Conforms To" },
      { key: "provenance", label: "Provenance" },
      { key: "wasGeneratedBy", label: "Was Generated By" },
    ],
  },
  {
    title: "Structure and Coding",
    emptyMessage: "No structure or coding metadata provided.",
    fields: [
      { key: "isStructured", label: "Is Structured" },
      { key: "codeValues", label: "Code Values" },
      { key: "codingSystem", label: "Coding System" },
      { key: "numberOfRecords", label: "Number of Records" },
      { key: "numberOfUniqueIndividuals", label: "Number of Unique Individuals" },
    ],
  },
];

const DISTRIBUTION_FIELD_DEFINITIONS = [
  { key: "uri", label: "URI" },
  { key: "description", label: "Description", emptyMessage: "No description provided" },
  { key: "format", label: "Format" },
  { key: "license", label: "License" },
  { key: "downloadURL", label: "Download URL" },
  { key: "accessURL", label: "Access URL" },
  { key: "mediaType", label: "Media Type" },
  { key: "byteSize", label: "Byte Size" },
  { key: "availability", label: "Availability" },
  { key: "issued", label: "Issued" },
  { key: "modified", label: "Modified" },
  { key: "conformsTo", label: "Conforms To" },
  { key: "accessService", label: "Access Service" },
];

const VARIABLE_FIELD_DEFINITIONS = [
  { key: "uri", label: "URI" },
  { key: "definition", label: "Definition", emptyMessage: "No definition provided" },
  { key: "dataType", label: "Data Type" },
  { key: "codingSystem", label: "Coding System" },
  { key: "valueDomain", label: "Value Domain" },
];

const DATASET_KNOWN_KEYS = new Set([
  "title",
  "distribution",
  "variables",
  ...DATASET_SECTION_DEFINITIONS.flatMap((section) =>
    section.fields.map((field) => field.key)
  ),
]);

const DISTRIBUTION_KNOWN_KEYS = new Set([
  "title",
  ...DISTRIBUTION_FIELD_DEFINITIONS.map((field) => field.key),
]);

const VARIABLE_KNOWN_KEYS = new Set([
  "name",
  ...VARIABLE_FIELD_DEFINITIONS.map((field) => field.key),
]);

function isEmptyValue(value) {
  if (value === null || value === undefined) return true;
  if (typeof value === "string" && value.trim() === "") return true;
  if (Array.isArray(value) && value.length === 0) return true;
  if (typeof value === "object" && !Array.isArray(value) && Object.keys(value).length === 0) return true;
  return false;
}

function isLikelyUrl(value) {
  return typeof value === "string" && /^https?:\/\//i.test(value);
}

function urlLabel(url) {
  try {
    const parsed = new URL(url);
    const lastPath = parsed.pathname
      .split("/")
      .filter(Boolean)
      .pop();

    return lastPath
      ? `${parsed.hostname} / ${decodeURIComponent(lastPath)}`
      : parsed.hostname;
  } catch {
    return url;
  }
}

function formatLabel(key) {
  if (!key) return "";

  const withoutPrefix = String(key).replace(/^[a-zA-Z0-9_-]+:/, "");

  return withoutPrefix
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/^./, (char) => char.toUpperCase());
}

function renderPrimitive(value) {
  if (isLikelyUrl(value)) {
    return (
      <a
        className={MetadataDisplayStyles.compactLink}
        href={value}
        target="_blank"
        rel="noreferrer"
        title={value}
      >
        {urlLabel(value)}
      </a>
    );
  }

  if (typeof value === "boolean") {
    return value ? "Yes" : "No";
  }

  return String(value);
}

function renderNested(value) {
  if (isEmptyValue(value)) {
    return <span className={MetadataDisplayStyles.muted}>No value provided</span>;
  }

  if (Array.isArray(value)) {
    if (value.length === 1) {
      return renderNested(value[0]);
    }

    return (
      <ul className={MetadataDisplayStyles.valueList}>
        {value.map((item, index) => (
          <li key={index}>{renderNested(item)}</li>
        ))}
      </ul>
    );
  }

  if (typeof value === "object") {
    const entries = Object.entries(value).filter(([, v]) => !isEmptyValue(v));

    if (entries.length === 0) {
      return <span className={MetadataDisplayStyles.muted}>No value provided</span>;
    }

    return (
      <div className={MetadataDisplayStyles.nestedObject}>
        {entries.map(([k, v]) => (
          <div key={k} className={MetadataDisplayStyles.nestedRow}>
            <span className={MetadataDisplayStyles.nestedLabel}>{formatLabel(k)}:</span>
            <span className={MetadataDisplayStyles.nestedValue}>{renderNested(v)}</span>
          </div>
        ))}
      </div>
    );
  }

  return renderPrimitive(value);
}

function renderField(label, value, emptyMessage) {
  const empty = isEmptyValue(value);

  if (empty && !emptyMessage) return null;

  return (
    <div className={MetadataDisplayStyles.fieldRow}>
      <div className={MetadataDisplayStyles.fieldLabel}>{label}</div>
      <div className={MetadataDisplayStyles.fieldValue}>
        {empty ? (
          <span className={MetadataDisplayStyles.muted}>{emptyMessage}</span>
        ) : React.isValidElement(value) ? (
          value
        ) : (
          renderNested(value)
        )}
      </div>
    </div>
  );
}

function renderFieldGroup(source, fieldDefinitions) {
  return fieldDefinitions.map(({ key, label, emptyMessage }) => (
    <React.Fragment key={key}>
      {renderField(label, source?.[key], emptyMessage)}
    </React.Fragment>
  ));
}

function collectExtraFields(source, knownKeys) {
  return Object.entries(source || {}).filter(
    ([key, value]) => !knownKeys.has(key) && !isEmptyValue(value)
  );
}

function renderExtraFields(title, extraFields) {
  if (extraFields.length === 0) {
    return null;
  }

  return (
    <div className={MetadataDisplayStyles.extraFields}>
      <div className={MetadataDisplayStyles.subsectionTitle}>{title}</div>
      {extraFields.map(([key, value]) => (
        <React.Fragment key={key}>
          {renderField(formatLabel(key), value)}
        </React.Fragment>
      ))}
    </div>
  );
}

function renderDistributionCard(distribution, index) {
  const title = distribution?.title || "Untitled Distribution";
  const extraFields = collectExtraFields(distribution, DISTRIBUTION_KNOWN_KEYS);

  return (
    <div key={index} className={MetadataDisplayStyles.distributionCard}>
      <div className={MetadataDisplayStyles.cardItemTitle}>{title}</div>
      {renderFieldGroup(distribution, DISTRIBUTION_FIELD_DEFINITIONS)}
      {renderExtraFields("Additional Distribution Fields", extraFields)}
    </div>
  );
}

function renderVariableCard(variable, index) {
  const title = variable?.name || `Variable ${index + 1}`;
  const extraFields = collectExtraFields(variable, VARIABLE_KNOWN_KEYS);

  return (
    <div key={index} className={MetadataDisplayStyles.variableCard}>
      <div className={MetadataDisplayStyles.cardItemTitle}>{title}</div>
      {renderFieldGroup(variable, VARIABLE_FIELD_DEFINITIONS)}
      {renderExtraFields("Additional Variable Fields", extraFields)}
    </div>
  );
}

function renderDistributions(distributionList) {
  if (!Array.isArray(distributionList) || distributionList.length === 0) {
    return <p className={MetadataDisplayStyles.sectionEmpty}>No distributions provided.</p>;
  }

  return distributionList.map(renderDistributionCard);
}

function renderVariables(variables) {
  if (!Array.isArray(variables) || variables.length === 0) {
    return <p className={MetadataDisplayStyles.sectionEmpty}>No variables provided.</p>;
  }

  return (
    <div className={MetadataDisplayStyles.variablesContainer}>
      {variables.map(renderVariableCard)}
    </div>
  );
}

const DatasetCard = ({ dataset }) => {
  const safeDataset = dataset || {};
  const datasetTitle = safeDataset.title || "Untitled Dataset";
  const extraFields = collectExtraFields(safeDataset, DATASET_KNOWN_KEYS);

  return (
    <div className={MetadataDisplayStyles.datasetCard}>
      <div className={MetadataDisplayStyles.datasetTitle}>{datasetTitle}</div>

      {DATASET_SECTION_DEFINITIONS.map(({ title, fields, emptyMessage }) => (
        <MetadataSection key={title} title={title} emptyMessage={emptyMessage}>
          {renderFieldGroup(safeDataset, fields)}
        </MetadataSection>
      ))}

      <MetadataSection title="Variables" emptyMessage="No variables provided.">
        {Array.isArray(safeDataset.variables) && safeDataset.variables.length > 0
          ? renderVariables(safeDataset.variables)
          : null}
      </MetadataSection>

      <MetadataSection title="Distributions" emptyMessage="No distributions provided.">
        {Array.isArray(safeDataset.distribution) && safeDataset.distribution.length > 0
          ? renderDistributions(safeDataset.distribution)
          : null}
      </MetadataSection>

      {extraFields.length > 0 && (
        <MetadataSection title="Additional Dataset Fields">
          {extraFields.map(([key, value]) => (
            <React.Fragment key={key}>
              {renderField(formatLabel(key), value)}
            </React.Fragment>
          ))}
        </MetadataSection>
      )}
    </div>
  );
};

export default DatasetCard;
