name: Dependency Review

on:
  pull_request:
    branches: [dev, main]

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependency Review
        id: depreview
        uses: actions/dependency-review-action@v4
        continue-on-error: true
        with:
          fail-on-severity: critical
          allow-licenses: MIT, Apache-2.0, BSD-3-Clause
